server:
  port: 8081
spring:
  datasource:
    # url: jdbc:mysql://172.22.31.124:3306/life-helper?useSSL=false
    url: jdbc:mysql://localhost:3306/life-helper?useSSL=false
    username: root
    # password: 123456
    password: root
    driver-class-name: com.mysql.jdbc.Driver
#      discovery:
#        cluster-name: HZ
mybatis:
  #标注实体类位置
  type-aliases-package: cn.itcast.user.pojo
  configuration:
    map-underscore-to-camel-case: true
  #标注待解析的mapper的xml文件位置
  mapper-locations: classpath:mapper/*.xml
  #标注实体类位置
logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
pattern:
  name: 本地环境local